Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# for PowerShell Core
steps:
- pwsh: ./berliner_wetter.ps1
- pwsh: ./func_folder_exists.ps1
- pwsh: ./get_timestamp.ps1


# for Windows PowerShell
- powershell: ./berliner_wetter.ps1
- powershell: ./func_folder_exists.ps1
- powershell: ./get_timestamp.ps1
